## Labels to apply to all resources
commonLabels:
  prometheus: planetarium

defaultRules:
  labels:
    release: prometheus

## Labels to match when selecting ServiceMonitors
prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: planetarium

## Adds label because commonLabels doesn't get applied
kube-state-metrics:
  prometheus:
    monitor:
      enabled: true
      additionalLabels:
        prometheus: planetarium

grafana:
  namespaceOverride: default
  adminPassword: teamsol
  grafana.ini:
    server:
      serve_from_sub_path: "true"
      root_url: "%(protocol)s://%(domain)s:/grafana/" # this lets Kubernetes auto set root_url value

  ingress:
    enabled: true
    path: /grafana
    ingressClassName: nginx
