global:
  scrape_interval: 10s

rule_files:
  - prometheus-rules.yaml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: planetarium
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - planetarium:8080
